# config.yaml

hydra:
  run:
    dir: ./logs3/${hydra.job.name}
  job:
    name: model:${loss.framework}-${loss.pretrained_on}_${loss.distance}_lr:${learning_rate}_bs:${dataloader.batch_size}_same-label:${dataloader.prob_same_label}_only-nir:${dataloader.prob_only_nir}_${now:%m-%d_%H-%M}
  

# Profiler
profile: True
profiler_logs_path: './logs/profiles/profile.log'


# Training
n_epoch: 20
learning_rate: 0.001
save_checkpoint: 20
validate: False

# Dataset properties
dataset:
  path: '/Users/robinin/face_recognition/datasets/renamed_clean'
  train_test_split: True
  nir_folder: 'NIR'
  vis_folder: 'VIS'
  load_same_label_pairs: './datasets/same_label_pairs.json'
  save_same_label_pairs: './datasets/same_label_pairs.json'
  load_subindex_for_label: './datasets/subindex_for_label.json'
  save_subindex_for_label: './datasets/subindex_for_label.json'
  load_train_test_splits: './datasets/splits'
  save_train_test_splits: './datasets/splits'

# Dataloader properties
dataloader:
  num_workers: 4
  prob_same_label: .5
  prob_only_nir: .5
  batch_size: 64
  pin_memory: True


# PDT
PDT:
  pool_features: 6

# Loss function
loss:
  distance: 'cosine' #'euclidean' or 'cosine'
  framework: 'sface' #can be 'facenet_pytorch' or 'sface'
  pretrained_on: 'vggface2' #if fw is facenet_pytorch it can be 'casia-webface' or 'vggface2'
  margin: 2
